### PR TITLE
Add Zigmod support

### PR DESCRIPTION
**Pull request by nektro**
it now supports all of koino's platforms

### CODE REVIEW

**Comment by nektro** [comment]
not sure why only macos is failing. seems to not like where the header files are

**Comment by kivikakk** [comment]
Yep, homebrew's a bit of a nuisance. Looking into it.

**Comment by kivikakk** [comment]
Hm, alright, turns out I don't have the time to look into this today. It's odd because `libpcre` itself builds with zigmod fine, so unclear what the issue is with including it as a dependency. Adding `- src: system_lib pcre` to koino's `zig.mod` does not help.

**Comment by nektro** [comment]
my only guess is it needs the name to be `libpcre` and doesn't understand `pcre` (since that's the name you use in `libpcre.zig`'s `build.zig`)

not sure if that's pkg-config or pcre or homebrew's fault

**Comment by nektro** [comment]
maybe linux working was a fluke

```
[nix-shell:~/other/gh/koino]$ pkg-config --cflags pcre
Package pcre was not found in the pkg-config search path.
Perhaps you should add the directory containing `pcre.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pcre' found

[nix-shell:~/other/gh/koino]$ pkg-config --cflags libpcre
-I/nix/store/hyn9wa71pcicvnjxik2ryb0rvay765mm-pcre-8.44-dev/include```

**Comment by kivikakk** [comment]
CI failure is because it looks like the Actions node got rate limited by GitHub … 🤦‍♀️ Retrying.

**Comment by kivikakk** [comment]
Success :) Thank you!! <3

**Pull request merged**
